/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  DecompositionRequest,  DecompositionResult,  ExecutiveBrief,  FactCheckRequest,  FactCheckResponse,  FactCheckResult,  Finding,  FollowUpSuggestion,  QualityMetrics,  ResearchGap,  ResearchRequest,  ResearchResult,  Resume,  Source,  SubQuery,  SynthesisRequest,  SynthesisResult,  ValidationRequest,  ValidationResult } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface DecompositionRequest {
      query?: string | null
      depth?: number | null
      validation?: ValidationResult | null
    }
    export interface DecompositionResult {
      primary_queries: SubQuery[]
      validation_queries: SubQuery[]
      edge_queries?: SubQuery[] | null
    }
    export interface ExecutiveBrief {
      title?: string | null
      date?: string | null
      research_question?: string | null
      key_findings: Finding[]
      critical_distinctions: string[]
      confidence_summary?: string | null
      strategic_implications: string[]
      recommended_actions: string[]
      read_time?: string | null
    }
    export interface FactCheckRequest {
      claims: string[]
      context?: string | null
    }
    export interface FactCheckResponse {
      results: FactCheckResult[]
      overall_accuracy?: number | null
      red_flags: string[]
    }
    export interface FactCheckResult {
      claim?: string | null
      verdict?: string | null
      explanation?: string | null
      sources: Source[]
      nuance?: string | null
    }
    export interface Finding {
      claim?: string | null
      confidence?: string | null
      sources: Source[]
      contradictions?: string[] | null
    }
    export interface FollowUpSuggestion {
      query?: string | null
      rationale?: string | null
      estimated_depth?: string | null
      priority?: number | null
    }
    export interface QualityMetrics {
      coverage_score?: number | null
      confidence_score?: number | null
      depth_score?: number | null
      overall_grade?: string | null
    }
    export interface ResearchGap {
      topic?: string | null
      importance?: string | null
      suggested_query?: string | null
    }
    export interface ResearchRequest {
      query?: string | null
      focus?: string | null
      boundary?: string | null
      depth?: number | null
      existing_knowledge?: string | null
    }
    export interface ResearchResult {
      summary?: string | null
      key_findings: Finding[]
      sources: Source[]
      gaps: ResearchGap[]
      follow_ups: FollowUpSuggestion[]
      quality?: QualityMetrics | null
      methodology?: string | null
    }
    export interface Resume {
      name?: string | null
      email?: string | null
      experience: string[]
      skills: string[]
    }
    export interface Source {
      url?: string | null
      title?: string | null
      snippet?: string | null
      source_type?: string | null
      authority_score?: number | null
      recency?: string | null
      bias_indicator?: string | null
    }
    export interface SubQuery {
      query?: string | null
      focus?: string | null
      priority?: number | null
      boundary?: string | null
    }
    export interface SynthesisRequest {
      original_query?: string | null
      research_results: ResearchResult[]
      fact_check?: FactCheckResponse | null
      output_format?: string | null
    }
    export interface SynthesisResult {
      executive_brief?: ExecutiveBrief | null
      detailed_analysis?: string | null
      source_appendix?: string | null
      quality?: QualityMetrics | null
    }
    export interface ValidationRequest {
      query?: string | null
      context?: string | null
    }
    export interface ValidationResult {
      is_clear?: boolean | null
      topics: string[]
      relationship?: string | null
      time_period?: string | null
      primary_sources: string[]
      recommended_structure?: string | null
      clarification_needed?: string[] | null
    }
}