/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum ContentLength {
  Short = "Short",
  Medium = "Medium",
  Long = "Long",
  Extended = "Extended",
}

export enum DocType {
  API = "API",
  Tutorial = "Tutorial",
  HowTo = "HowTo",
  Reference = "Reference",
  Conceptual = "Conceptual",
  Troubleshooting = "Troubleshooting",
  Changelog = "Changelog",
}

export enum EditFocus {
  Grammar = "Grammar",
  Clarity = "Clarity",
  Conciseness = "Conciseness",
  Tone = "Tone",
  Structure = "Structure",
  All = "All",
}

export enum EmailType {
  Introduction = "Introduction",
  FollowUp = "FollowUp",
  Request = "Request",
  ThankYou = "ThankYou",
  Apology = "Apology",
  Announcement = "Announcement",
  Proposal = "Proposal",
  ColdOutreach = "ColdOutreach",
}

export enum WritingTone {
  Professional = "Professional",
  Casual = "Casual",
  Technical = "Technical",
  Persuasive = "Persuasive",
  Academic = "Academic",
  Friendly = "Friendly",
}

export interface BlogPost {
  title: string
  subtitle?: string | null
  meta_description: string
  tags: string[]
  estimated_read_time: number
  sections: BlogSection[]
  call_to_action?: string | null
  
}

export interface BlogRequest {
  topic: string
  target_audience?: string | null
  tone?: WritingTone | null
  length?: ContentLength | null
  key_points?: string[] | null
  include_examples?: boolean | null
  seo_keywords?: string[] | null
  
}

export interface BlogSection {
  heading: string
  content: string
  key_points?: string[] | null
  
}

export interface Change {
  type: string
  description: string
  before?: string | null
  after?: string | null
  
}

export interface CodeExample {
  language: string
  description: string
  code: string
  
}

export interface DecompositionRequest {
  query: string
  depth: number
  validation: ValidationResult
  
}

export interface DecompositionResult {
  primary_queries: SubQuery[]
  validation_queries: SubQuery[]
  edge_queries?: SubQuery[] | null
  
}

export interface DocSection {
  heading: string
  content: string
  subsections?: DocSection[] | null
  
}

export interface Documentation {
  title: string
  overview: string
  sections: DocSection[]
  code_examples?: CodeExample[] | null
  related_topics?: string[] | null
  last_updated: string
  
}

export interface DocumentationRequest {
  topic: string
  doc_type?: DocType | null
  target_audience?: string | null
  include_code_examples?: boolean | null
  programming_language?: string | null
  existing_content?: string | null
  
}

export interface EditRequest {
  content: string
  focus?: EditFocus | null
  target_tone?: WritingTone | null
  preserve_voice?: boolean | null
  max_word_count?: number | null
  
}

export interface EditedContent {
  original_word_count: number
  edited_word_count: number
  content: string
  changes_made: Change[]
  readability_score: number
  
}

export interface Email {
  subject: string
  greeting: string
  body: string
  closing: string
  signature?: string | null
  tone_used: WritingTone
  
}

export interface EmailRequest {
  purpose: string
  recipient: string
  context?: string | null
  email_type?: EmailType | null
  tone?: WritingTone | null
  key_points?: string[] | null
  sender_name?: string | null
  sender_title?: string | null
  
}

export interface ExecutiveBrief {
  title: string
  date: string
  research_question: string
  key_findings: Finding[]
  critical_distinctions: string[]
  confidence_summary: string
  strategic_implications: string[]
  recommended_actions: string[]
  read_time: string
  
}

export interface FactCheckRequest {
  claims: string[]
  context: string
  
}

export interface FactCheckResponse {
  results: FactCheckResult[]
  overall_accuracy: number
  red_flags: string[]
  
}

export interface FactCheckResult {
  claim: string
  verdict: string
  explanation: string
  sources: Source[]
  nuance?: string | null
  
}

export interface Finding {
  claim: string
  confidence: string
  sources: Source[]
  contradictions?: string[] | null
  
}

export interface FollowUpSuggestion {
  query: string
  rationale: string
  estimated_depth: string
  priority: number
  
}

export interface QualityMetrics {
  coverage_score: number
  confidence_score: number
  depth_score: number
  overall_grade: string
  
}

export interface ResearchGap {
  topic: string
  importance: string
  suggested_query: string
  
}

export interface ResearchRequest {
  query: string
  focus: string
  boundary: string
  depth: number
  existing_knowledge?: string | null
  
}

export interface ResearchResult {
  summary: string
  key_findings: Finding[]
  sources: Source[]
  gaps: ResearchGap[]
  follow_ups: FollowUpSuggestion[]
  quality: QualityMetrics
  methodology: string
  
}

export interface Resume {
  name: string
  email: string
  experience: string[]
  skills: string[]
  
}

export interface Source {
  url: string
  title: string
  snippet: string
  source_type: string
  authority_score: number
  recency: string
  bias_indicator?: string | null
  
}

export interface SubQuery {
  query: string
  focus: string
  priority: number
  boundary: string
  
}

export interface SynthesisRequest {
  original_query: string
  research_results: ResearchResult[]
  fact_check?: FactCheckResponse | null
  output_format: string
  
}

export interface SynthesisResult {
  executive_brief: ExecutiveBrief
  detailed_analysis: string
  source_appendix: string
  quality: QualityMetrics
  
}

export interface TranslateRequest {
  content: string
  target_language: string
  source_language?: string | null
  preserve_formatting?: boolean | null
  localize?: boolean | null
  domain?: string | null
  
}

export interface TranslatedContent {
  source_language: string
  target_language: string
  original_content: string
  translated_content: string
  translation_notes?: string[] | null
  cultural_adaptations?: string[] | null
  
}

export interface ValidationRequest {
  query: string
  context?: string | null
  
}

export interface ValidationResult {
  is_clear: boolean
  topics: string[]
  relationship: string
  time_period: string
  primary_sources: string[]
  recommended_structure: string
  clarification_needed?: string[] | null
  
}
